name: "Create or update PR comment"
description: "Create or update PR comment"
inputs:
  pr-number:
    description: "The number of the pull request in which to search."
    required: true
  target-author:
    description: "The GitHub user name of the comment author."
    required: true
  target-body-includes:
    description: "A string to search for in the body of comments."
    required: true
  body:
    description: "A string of new comment body."
    required: true

runs:
  using: "composite"
  steps:
    - name: Find PR comment
      uses: peter-evans/find-comment@v1
      id: find-comment
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: ${{ inputs.target-author }}
        body-includes: ${{ inputs.target-body-includes }}

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        body: ${{ inputs.body }}
        edit-mode: replace
