name: "Get PR data from commit hash"
description: "Get PR number and title from commit hash"

inputs:
  commit:
    description: "Target commit hash"
    required: true

outputs:
  number:
    value: ${{ fromJson(steps.get-pr-data.outputs.result).number }}
    description: "PR number"
  title:
    value: ${{ fromJson(steps.get-pr-data.outputs.result).number }}
    description: "PR title"

runs:
  using: "composite"
  steps:
    - name: "Get PR number from commit sha"
      uses: actions/github-script@v6
      id: get-pr-data
      with:
        script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: "${{ inputs.commit }}",
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];
