name: "Get PR data from commit hash"
description: |
  "Get PR number and title from commit hash"
  "NOTE: required permissions are: contents: read, pull-requests: read"

inputs:
  commit:
    description: "Target commit hash"
    required: true

outputs:
  number:
    value: ${{ steps.find-pr.outputs.result && fromJson(steps.find-pr.outputs.result).number || null }}
    description: "PR number"
  title:
    value: ${{ steps.find-pr.outputs.result && fromJson(steps.find-pr.outputs.result).title || null }}
    description: "PR title"

runs:
  using: "composite"
  steps:
    - name: "Get PR number from commit sha"
      uses: actions/github-script@v6
      id: find-pr
      with:
        script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: "${{ inputs.commit }}",
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];
