name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      front:
        description: "Release front"
        required: true
        default: false
        type: boolean
      api:
        description: "Release api"
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          depth: 0

      # - name: Set up Git
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get branch name
        id: get_branch_name
        run: echo "name=release/$(date +'%Y-%m-%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          git switch -c ${{ steps.get_branch_name.outputs.name }}
          git push origin ${{ steps.get_branch_name.outputs.name }}

      - name: Create PR Content
        id: create_pr_content
        run: |
          title=$(echo ${{ steps.get_branch_name.outputs.name }} | sed -e 's/release/Release/g' -e 's/\// /g')
          echo "title=$title" >> $GITHUB_OUTPUT  

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "## Release Targets" >> $GITHUB_OUTPUT
          if [ "${{ github.event.inputs.front }}" = "true" ]; then
            echo "- Front" >> $GITHUB_OUTPUT
          fi
          if [ "${{ github.event.inputs.api }}" = "true" ]; then
            echo "- API" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release pr
        run: |
          gh pr create \
          --title "${{ steps.create_pr_content.outputs.title}}" \
          --body "${{ steps.create_pr_content.outputs.body }}" \
          --base master

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: "Release"
      #     branch: ${{ steps.get_branch_name.outputs.name }}
      #     base: master
      #     title: "Release ${{ steps.get_branch_name.outputs.name }}"
      #     body: ${{ steps.create_pr_description.outputs.description }}
