name: Get PR Number

on:
  push:
    branches:
      - try/**
      - preview/**
  workflow_dispatch:

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: ./.github/actions/get-pr-from-commit
        id: get-pr-data
        with:
          commit: ${{ github.sha }}

      - name: Notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: notify
          SLACK_COLOR: good
          SLACK_TITLE: Get PR Number
          # リポジトリのurlを取得し、結合してreleaseへのリンクを作成する
          SLACK_MESSAGE: "PR: ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.get-pr-data.outputs.number }}"
