name: Notify on new release

on:
  push:
    branches:
      - preview/*

jobs:
  get-pr-number:
    name: Get PR Number
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
      - name: Pull Request data
        run: |
          echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: get-pr-number
    timeout-minutes: 5
    steps:
      - name: Notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: notify
          SLACK_COLOR: good
          SLACK_TITLE: Get PR Number
          # リポジトリのurlを取得し、結合してreleaseへのリンクを作成する
          SLACK_MESSAGE: "PR: ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.get-pr-number.outputs.PR }}"
