name: Get PR Number

on:
  push:
    branches:
      - main
      - try/**
      - preview/**
  workflow_dispatch:

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: notify
          SLACK_COLOR: good
          SLACK_TITLE: Get PR Number
          # リポジトリのurlを取得し、結合してreleaseへのリンクを作成する
          SLACK_MESSAGE: "PR: ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.get-pr-data.outputs.number || 'not found' }}"

      - name: Find PR
        uses: ./.github/actions/get-pr-from-commit
        id: get-pr-data
        with:
          commit: ${{ github.sha }}

      - name: Get datetime for now
        id: datetime
        run: echo "::set-output name=value::$(date)"
        env:
          TZ: Asia/Tokyo

      - name: Create or update comment
        uses: ././.github/actions/create-or-update-pr-comment
        if: steps.get-pr-data.outputs.number != null
        with:
          pr-number: ${{ steps.get-pr-data.outputs.number }}
          target-author: github-actions[bot]
          target-body-includes: "Test"
          body: "Test comment (created at ${{ steps.datetime.outputs.value }})"
