name: Get PR Number

on:
  push:
    branches:
      - preview/**
  workflow_dispatch:

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/github-script@v6
        id: get-pr-data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
      - name: Notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: notify
          SLACK_COLOR: good
          SLACK_TITLE: Get PR Number
          # リポジトリのurlを取得し、結合してreleaseへのリンクを作成する
          SLACK_MESSAGE: "PR: ${{ github.server_url }}/${{ github.repository }}/pull/${{ fromJson(steps.get-pr-data.outputs.result).number }}"
